### ISSUE TITLE
TypeScript Definitions *please*

### ISSUE THREAD

**Issue by lelong37** [ericf/express-handlebars#102]
Could you be so kind to create the TypeScript Definitions for this wonderful package?

For additional TypeScript context:

http://definitelytyped.org/
https://github.com/borisyankov/DefinitelyTyped

I would love to do a pull request and help, however this is my first day using express-handlebars, coming from vash engine, strict typing, build/compile time errors, and real intellisense would have been a great help. TypeScript could help you guys as well, it's just (over simplification here) ES5, ES6 - next version of JS, with strict typing) compiled to JS that will run in modern browsers today.

**Comment by ericf** [comment]
How do TypeScript definitions work in Node.js and with npm modules?

**Comment by ericf** [comment]
Closing this, if you'd like to reopen this discussion please open a PR for this.
