### ISSUE TITLE
Sharing compiled templates.

### ISSUE THREAD

**Issue by Atsman** [ericf/express-handlebars#110]
Hi,

Could somebody give a example, how can i get compiled template on client?

**Comment by jasonmit** [comment]
The advanced example covers this: https://github.com/ericf/express-handlebars/tree/05e8a8addd7f1deaaefc545bdf8cec9da2c0006f/examples/advanced

https://github.com/ericf/express-handlebars/blob/05e8a8addd7f1deaaefc545bdf8cec9da2c0006f/examples/advanced/server.js#L14-L15

**Comment by ericf** [comment]
Thanks @jasonmit.
