### ISSUE TITLE
Nesting layouts

### ISSUE THREAD

**Issue by omarfouad** [ericf/express-handlebars#115]
Is there a way to nest a layout inside of another? For example:

```
default.hsb
-- postLayoout.hbs
---- {{{body}}}

```

Thanks in advance.

**Comment by ericf** [comment]
Not that's built into this package. You'd have to do this manually using partials and/or block helpers.

What's different between your `default.hbs` and `postLayout.hbs` layouts?

**Comment by omarfouad** [comment]
The `postLayout.hbs` has some specific UI elements just for a page that has a post. So, the article would be yield in that `postLayout`. The `postLayout` then would be yield in the `default` layout (the actual page with the doctype, header and footer

**Comment by Ghosh** [comment]
@omarfouad Hey, did you mange to nest the layouts like you desired? I am trying the same, any tips on how this can be done? Thanks!

**Comment by omarfouad** [comment]
@Ghosh No, I used an alternative called here: https://github.com/barc/express-hbs

**Comment by robertwbradford** [comment]
+1. Nesting is a good thing.
