### ISSUE TITLE
contentFor / block helpers can't be used multiple times?

### ISSUE THREAD

**Issue by bradvogel** [ericf/express-handlebars#122]
I have the following block helper:

```
{{#contentFor "pageTitle"}}my page{{/contentFor}}
```

and then I use the block helper twice in the parent layout:

```
<title>{{block 'pageTitle'}}</title>
<meta name="og:title" content="{{block 'pageTitle'}}">
```

However, the resulting HTML is:

```
<title>my page</title>
<meta name="og:title" content="">
```

It looks like a block can only be used once. This seems like a bug, right?

**Comment by ericf** [comment]
I'm not sure, you're using custom helpers here. I'd need to see the implementations of these helpers in order to help. Can you share those?

**Comment by bradvogel** [comment]
My apologies - I filed this against the wrong repo. Real issue here: https://github.com/barc/express-hbs/issues/78
