### ISSUE TITLE
How could I work with handlebars-layouts

### ISSUE THREAD

**Issue by x4storm** [ericf/express-handlebars#129]
express-handlebars don't have registerHelpers method。

**Comment by x4storm** [comment]
https://github.com/shannonmoeller/handlebars-layouts

**Comment by ericf** [comment]
Handlebars is accessible via the `handlebars` prop: https://github.com/ericf/express-handlebars#handlebarsrequirehandlebars

**Comment by Kostanos** [comment]
The same issue as #242
