### ISSUE TITLE
Compile views when Node app is launched & compile when requested

### ISSUE THREAD

**Issue by MarkusPint** [ericf/express-handlebars#131]
I want to be able to manually update the cache of compiled templates. First they should be compiled in the back-end when the Node app is launched and then whenever page content (ie. variables that are passed to the templates) is updated from the CMS.

And then, basically, the client should be served a regular HTML page.

I don't want to compile the views again every time a client requests it.

The goal is to avoid excessive DB requests.

How should I go about doing that?

**Comment by ericf** [comment]
Handlebars has two forms of compiled templates: _compiled_ for rendering, and _precompiled_ for portability and re-hydrating and rendering somewhere else, like the browser. If you want to use the same templates on the server and in the browser you'll need to compile them twice.

See the [Advanced Example](https://github.com/ericf/express-handlebars#advanced-usage) for how to do this.
