### ISSUE TITLE
Feature: contentFor block helper

### ISSUE THREAD

**Issue by shellscape** [ericf/express-handlebars#15]
Love the project. By far the easiest to get going so far for this node.js/express newbie. 

The express-hbs project has a really neat feature I'd love to see added. I'm not well enough versed yet to create this and file a pull request. The _contentFor_ helper is basically equiv to content placeholders in asp.net and very useful. Basically allows to adding content to a parent template/layout. Here's the usage from express-hbs

layout.handlebars

```
{{{block "pageScripts"}}}
```

index.handlebars

```
{{#contentFor "pageScripts"}}
  CONTENT HERE
{{/contentFor}}
```

Is this something we can get added, or would it be possible to get a helper function we can add as middleware?

**Comment by MacgyverMartins** [comment]
It doesn't work for me. It just returns a string inside the HTML and nothing happens

**contact.hbs**
```
{{#contentFor "pageScripts"}}
  <script src="js/pace.min.js"></script>
  <script src="js/wow.min.js"></script>
{{/contentFor}}
```
**main.hbs**
``` 
{{block "pageScripts"}}
```

**Comment by panlw** [comment]
Great!

**Comment by ignacionr** [comment]
This is working really well. Cheers!!

**Comment by rajitha-bandara** [comment]
To properly run js, instead of displaying it,
I needed to change the notation from
{{block "pageScripts"}}  to {{{block "pageScripts"}}}
