### ISSUE TITLE
Insecure dependencies

### ISSUE THREAD

**Issue by chrisfosterelli** [ericf/express-handlebars#166]
[David DM](https://david-dm.org/ericf/express-handlebars) for express-handlebars is warning that there is a vulnerability in this handlebars version, which should be updated to mitigate.

![image](https://cloud.githubusercontent.com/assets/2072672/12129166/ad5c8204-b3b6-11e5-983a-ce12f8d6d3fd.png)

The badge on this project's readme currently says "insecure".

**Comment by sahat** [comment]
Fixed in 2.0.2.

**Comment by chrisfosterelli** [comment]
Great thank you!
