### ISSUE TITLE
How to use multiple helper files?

### ISSUE THREAD

**Issue by prabhg** [ericf/express-handlebars#175]
I have my helper functions defined across multiple files. Is there a way to define multiple helper files in config while creating hbs instance?

I tried passing an array to "helpers" property of the config but it did not work.

var hbs = exphbs.create({
    defaultLayout: 'main',
    extname: '.hbs',
   **helpers: [hbsHelpers, hbsBlockHelpers]**
});

**Comment by dynnamitt** [comment]
conf = {
helpers: require('lodash').assign hbsHelpers,hbsBlockHelpers
}

**Comment by prabhg** [comment]
Thanks! That works! Closing the issue
