### ISSUE TITLE
How to get SUM in {{ ? }}

### ISSUE THREAD

**Issue by joviqiao** [ericf/express-handlebars#186]
data sometime need add , subtract , multiply and divide,
How to do it? if i create helper, numerous functions...:
data:
[{name:user1,buytimes:2},{name:user2,buytimes:4},...]
now, i need get all of buytimes, How to do it in page?

**Comment by hguillermo** [comment]
You need a helper. Check here: https://github.com/assemble/handlebars-helpers

**Comment by joviqiao** [comment]
@hguillermo Thx, it work, but
 {{sum [user.tj1num,user.tj2num,user.tj3num] }}
 {{sum "[{{user.tj1num}},{{user.tj2num}},{{user.tj3num}}]" }}
How to create array can get sum ?

**Comment by hguillermo** [comment]
You are trying to use a helper inside a helper. The syntax is different. Check this: http://stackoverflow.com/questions/14781916/is-it-possible-to-nest-helpers-inside-the-options-hash-with-handlebars

If not you can create your own helper and pass the array and return the sum or whatever you need.

**Comment by joviqiao** [comment]
Thx

**Comment by joviqiao** [comment]
{{ user }}
	<tr>
		<td>{{user.Phone}}</td>
		<td>{{user.name}}</td>
		<td>
			<select class="trendSet">
				<option {{if user.trend eq 0}}selected="selected"{{/if}} value="0">No trend</option>
				<option {{if user.trend eq 1}}selected="selected"{{/if}} value="1">trend</option>
				<option {{if user.trend eq 2}}selected="selected"{{/if}} value="2">wait</option>
				<option {{if user.trend eq 3}}selected="selected"{{/if}} value="3">want</option>
			</select>
		</td>
	</tr>

Hi @hguillermo  above, my problem is: user.trend ( backend data ) judge eq number, like ==, + - * / , there have backend data. Thx

**Comment by shone83** [comment]
@hguillermo How to write my own sum array helper function and use it in {{sum array}} handlebars without install handlebars-helpers? Can you help?

**Comment by shone83** [comment]
Ok, you said it's pretty simple so I thought that could do it.
