### ISSUE TITLE
Developer comments only?

### ISSUE THREAD

**Issue by alvarotrigo** [ericf/express-handlebars#203]
Is it possible to add comments in the views that won't get outputted ? 
Just as in PHP we can do:

```php
<?php
/*
* This comment won't get printed in this view
*/
?>
<div class="aaa">Demo</div>
```

**Comment by robinhouston** [comment]
```{{!-- This comment won't get printed in this view --}}```

**Comment by alvarotrigo** [comment]
@robinhouston thanks! Where did you get that from?

**Comment by robinhouston** [comment]
http://handlebarsjs.com/#comments

**Comment by alvarotrigo** [comment]
Is that a new feature? I can't believe I missed it! :D

**Comment by robinhouston** [comment]
Ha ha, it’s easy to miss things! It looks as though`{{!-- this comment syntax --}}` was [added in 2012](https://github.com/wycats/handlebars.js/commit/a927a9b0adc39660f0794b9b210c9db2f7ddecd9) but `{{! this comment syntax }}` is considerably older.
