### ISSUE TITLE
LayoutDir path seems to be in relation to current working directory?

### ISSUE THREAD

**Issue by subserver** [ericf/express-handlebars#212]
Hi,

Found an problem with the library, forgive me if I am mistaken.
I have the following directory structure
```
project_dir
└───index.js    
└───app                         
    └───views     
    │        └───home.hbs
    │        └───layouts
    │             └───main.hbs
    └───server.js  
```

and the following construction code inside server.js
```
const exphbs = require('express-handlebars');

app.engine('.hbs', exphbs({
    defaultLayout: 'main',
    extname: '.hbs',
}));

app.set('view engine', '.hbs');
app.set('views', path.join(__dirname, 'views'));
```

The issue that I am having is that if I run `node server.js ` or `node ../index.js` from within the "app" directory then the entire server runs fine. However, if I run `node ./app/server.js` or `node index.js` from within the project_dir directory, then I get the following error
```
Error: ENOENT: no such file or directory, open '<REMOVED>/project_dir/views/layouts/main.hbs'
```

which is the wrong place to be looking for the views in the first place? 

I have tried specifying a layoutDir, but get the same error message regardless.
```
app.engine('.hbs', exphbs({
    defaultLayout: 'main',
    extname: '.hbs',
    layoutDir: path.join(__dirname, 'views/layouts/')
}));
```
results in the same problem

**Comment by subserver** [comment]
New day, and I just realised that I was in error, should have used layoutsDir instead of layoutDir in the configuration

Sheepishly closed this issue :')

**Comment by madibalive** [comment]
Hi solution is to use "/" before dir to public folder 
example 
`<link rel='stylesheet' href='/stylesheets/public-style.css' />`
`<script src="/javascripts/uikit.min.js"></script>`
this is use absolute url , to the public directory
not 
`<link rel='stylesheet' href='stylesheets/public-style.css' />`
`<script src="javascripts/uikit.min.js"></script>` 
it use  url as base , so u get wrong references
