### ISSUE TITLE
Out of date deps

### ISSUE THREAD

**Issue by pizza-r0b** [ericf/express-handlebars#235]
Is anyone maintaining this package? Dependencies seem to be out of date.

**Comment by AliSawari** [comment]
Guess it's abandoned :thinking:
The last commit belongs to 2016 :neutral_face:

**Comment by NIghel123** [comment]
Are there any similar alternatives to this package?

**Comment by AliSawari** [comment]
you can use **[express-hbs](https://www.npmjs.com/package/express-hbs)**
but generally you can fork this rep and update the packages for yourself.

**Comment by pizza-r0b** [comment]
@AliSawari express-hbs last commit was two years ago.

**Comment by NIghel123** [comment]
what would I do after forking to update the packages myself? I am pretty new to node.js...

**Comment by AliSawari** [comment]
@NIghel123 first you need to clone the rep, then you can run **`npm update`** to update the packages to the latest version.

**Comment by NIghel123** [comment]
@AliSawari I type `npm update express-handlebars` after i downloaded the package via npm? How do I know it didn't break anything? Greets

**Comment by AliSawari** [comment]
@NIghel123 no, you only need to run `npm update`. it doesn't  break anything unless if you are using a deprecated API or the package source itself (e.g express-handlebars) is using deprecated API and there's a new implementation available in the dependencies. for more information about npm commands, [see here](https://docs.npmjs.com/cli-documentation/).

**Comment by UziTech** [comment]
you will need to fork the repo and use the [github url](https://docs.npmjs.com/files/package.json#github-urls) or [git url](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) in the `express-handlebars` version

i.e.
```js
  dependencies: {
    "express-handlebars": "YourUsername/express-handlebars"
  }
```

**Comment by sahat** [comment]
https://www.npmjs.com/package/express-handlebars/v/3.0.1 contains updated dependencies as of 02/20/2019.
