### ISSUE TITLE
Project tagline is confusing

### ISSUE THREAD

**Issue by insanity54** [ericf/express-handlebars#236]
"A Handlebars view engine for Express which doesn't suck."

Why does the other handlebars view engine suck? Why should I use this one over that one? The Readme does not give enough details on this.

**Comment by AliSawari** [comment]
Agreed, it could be something better like
**A better Handlebars view engine for Express**

or maybe the other Handlebars view engines suck, I dont know, I didnt try them :sweat_smile:

**Comment by sahat** [comment]
I am just a maintainer of this repo so can't change the tag line, and I haven't seen Eric active much anymore. I am going to close this issue.
