### ISSUE TITLE
HIGH SEVERITY vulnerability  [snyk] express prototype pollution [security]

### ISSUE THREAD

**Issue by iwaduarte** [ericf/express-handlebars#250]
✗ High severity vuln found in handlebars@4.0.13,
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-HANDLEBARS-174183
    From: nodemailer-express-handlebars@3.0.0 > express-handlebars@3.0.2 > handlebars@4.0.13

Is there anyway to refer to handlebars@4.0.14 and fix this vulnerability ?

**Comment by sahat** [comment]
Handlebars dependency has been upgraded to 4.1.2 in the latest release.
