### ISSUE TITLE
Nodemailer + Handlebars + NextJS - The correct path

### ISSUE THREAD

**Issue by ghost** [ericf/express-handlebars#269]
I'm experiencing problems to find the right path settings in `production` for my nodemailer/handlebars setup.
The transporter is connected to an API request in order to send an automatic email.

In `development` I'm leaving the configuration as is, so basically I have this situation:

```
module.exports.ViewOption = (transport, hbs) => {
  transport.use('compile', hbs({
    viewEngine: {
      extname: '.hbs',
      partialsDir: 'static/js/mail/views/email',
      layoutsDir: 'static/js/mail/views',
      defaultLayout: 'contacts'
    },
    viewPath: 'static/js/mail/views',
    extName: '.hbs'
  }));
}
```

No problems here, everything works fine.

On `Now` instead, I'm receiving this exception:

![e14c1fe1-d069-417f-bb3b-4280cce1193e-Screenshot%202019-11-06%20at%2010 47 57](https://user-images.githubusercontent.com/12085296/68772838-cdd67b00-062a-11ea-863d-5b80ff016e84.png)

The request returns an ok response as you can see here:

![9b9308ff-40e7-448f-9649-097d2414bd67-Screenshot%202019-11-06%20at%2010 48 10](https://user-images.githubusercontent.com/12085296/68772866-d6c74c80-062a-11ea-8a04-4fef4ae95a99.png)

So I concluded that the problem is related to the wrong path set on transporter config. I can't live it like on `dev` because it redirects on `/var/tasks`. The problem is that I've tried different ways to locate the file path correctly, without success:

- Using `__dirname +'<path>'`
- Placing it in plain such as `/<path>...`
- Setting the one inside `_next` production dir: `/_next/static/....`

This is my current filesystem:

![3e9a6197-28e3-4044-aff4-861fc2090789-Screenshot%202019-11-06%20at%2010 49 25](https://user-images.githubusercontent.com/12085296/68772928-ee9ed080-062a-11ea-88fc-28791ca76838.png)
![9e614c26-ad2d-4fce-a7be-b1f30795e3d3-Screenshot%202019-11-06%20at%2010 48 39](https://user-images.githubusercontent.com/12085296/68772929-ee9ed080-062a-11ea-8e75-0cd8697c37f4.png)

As you can see, I've the config file both inside on `/static/js/mail/config` than `/_next/static/js/mail/config`. None of both worked, the call responses every time with the same error, independently by its path.

This is my current ```now.json``` if it could be helpful:
```
{
  "public": false,
  "name": "LC",
  "version": 2,
  "routes": [{
    "src": "/resume",
    "dest": "https://lucacattide.dev/static/html/resume.html"
  }, {
    "src": "/robots.txt",
    "dest": "https://lucacattide.dev/static/robots.txt"
  }, {
    "src": "/sitemap.xml",
    "dest": "https://lucacattide.dev/static/sitemap.xml"
  }, {
    "src": "^/service-worker.js$",
    "dest": "/_next/static/service-worker.js",
    "headers": {
      "cache-control": "public, max-age=43200, immutable",
      "Service-Worker-Allowed": "/"
    }
  }],
  "env": {
    "RECAPTCHA_SECRET_KEY": "@recaptcha",
    "SMTP_SERVICE_HOST": "@smtp_host",
    "SMTP_SERVICE_PORT": "@smtp_port",
    "SMTP_SERVICE_SECURE": "@smtp_secure",
    "SMTP_USER_NAME": "@smtp_name",
    "SMTP_USER_PASSWORD": "@smtp_password",
    "SMTP_LOG_NAME": "@smtp_log"
  },
  "github": {
    "enabled": true,
    "autoAlias": false
  }
}
```

Anyone experienced this before or could help me in some way?

Thanks in advance

**Comment by UziTech** [comment]
are you looking for [`nodemailer-express-handlebars`](https://github.com/yads/nodemailer-express-handlebars)?

I'm not sure if this package will work in nodemailer.

**Comment by ghost** [comment]
Yes. its maintainer bounced me here because [as he stated here](https://github.com/yads/nodemailer-express-handlebars/issues/32#issuecomment-558739573), ```nodemailer-express-handlebars``` is a plugin that ensures only the passage of configuration and no more.
So I can confirm by my current local environment that works perfectly as expected. As I said in my earlier post, the problem is the incorrect redirection on ```production``` in a lambda-setting environment ([Zeit.co](https://zeit.co) in my case, which reflects AWS Lambda).

**Comment by UziTech** [comment]
So the error is that it cannot find the file `/static/js/mail/views/contact.hbs`?

It looks like it is an issue with an absolute path.

When it is set to `_dirname + '/static/...` that is prepending the `_dirname` of the `email.js` file so it will be `'.../static/js/lib/mail/config' + '/static/...'`

try using [`path.resolve`](https://nodejs.org/api/path.html#path_path_resolve_paths) to get the actual absolute path

```js
const path = require('path')
...
      viewPath: path.resolve(_dirname, '../views');
```

**Comment by ghost** [comment]
Thanks for the tip @UziTech.
Unfortunately, this is what I'm getting:
> { [Error: ENOENT: no such file or directory, open '/views/contacts.hbs']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/views/contacts.hbs' }

this configuring it as ```path.resolve(__dirname, '/views/email')```. The folder structure is this:
```
/
-- static/
   |-- js/
        |-- mail/
            |-- views/ <--- Templates folder
                |-- email/ <--- Partials directory
                     |-- bar.hbs <--- Partial template
                |-- foo.hbs <--- defaultLayout
            |-- email.js <--- Configuration file
```
Currently ```__dirname``` is returning me the root (```/```). So other tries like ```path.resolve(__dirname, '/static/js/mail/views/email')``` render the exception as well
I'm still trying on ```localhost``` but I'm using a script that reproduces the live environment, so it reflects the real example. Doing the final test on hosting ```production``` env too confirm this.

**Comment by UziTech** [comment]
> Currently `__dirname` is returning me the root (`/`)

That seems to be the problem. According to the documentation [__dirname](https://nodejs.org/docs/latest/api/modules.html#modules_dirname) should return the current module file directory's absolute path with symlinks resolved.

Somehow you need to find the actual absolute path to the `viewPath`.

**Comment by ghost** [comment]
At last I found the cause of ```__dirname``` misconfiguration, related to the _Webpack_ configuration. As suggested on StackOverflow, by deactivating it on _Webpack_, as follows:
```
{
  node: {
    __dirname: false
  }
}
```
Only the ```__dirname``` from Node configuration is being used on client-side.

But, unfortunately, this doesn't solve my situation, because _NextJS_ uses more than one _Webpack_ config - both for server-side than client-side - so in my case, if I try to modify the client-side one, the returned path points to _NextJS_ ```/pages/api``` folder.

Due to the fact that by the serverless environment of my current Hosting - [Zeit.co](https://zeit.co) - is impossible to my to set up a proper ```express``` custom server as I would, I finally opted for a third-party service - [EmailJS](https://emailjs.com).

Thank you anyway for your helpful tips and patience.
