### ISSUE TITLE
Looping through object arrays

### ISSUE THREAD

**Issue by malikolabiyi** [ericf/express-handlebars#279]
I have this list:

`const list = [{"name":"Elon Musk","company":"Tesla"},{"name":"Bill Gate","company":"Microsoft"}]`

I want to loop each of them and get their names and the company's value.

I have tried this, but it didn't work:

`{{#each list}} 
   {{#each this}}
       <p>{{name}}</p>
       <p>{{company}}</p>
   {{/each}}
{{/each}}
`

**Comment by UziTech** [comment]
seems like a question for [`handlebars`](https://github.com/wycats/handlebars.js/) this project just adds handlebars to the express view engine.

You should try:

```handlebars
{{#each list}} <p>{{name}}</p> <p>{{company}}</p> {{/each}}
```

**Comment by malikolabiyi** [comment]
Man, you're a lifesaver... I have been on this issue for ages. Thanks in folds!

And sorry for this misconception, I thought the handlebars and express-handlers are the same.

I am really happy I got it resolved, thanks again!
