### ISSUE TITLE
Handlebars clear/reset cache

### ISSUE THREAD

**Issue by titus7lite** [ericf/express-handlebars#280]
Hi,

i am trying to find a way to clear/reset the cache of views in order to allocate/hotswap newly created changes during runtime. I cant seem to find a way to do it as it looks to be protected. Did i miss something and such a functionality is currently achievable somehow? or should i fork the repo and make the cache puplic?

kind regards

**Comment by UziTech** [comment]
new development of express-handlebars is on a new repo [express-handlebars/express-handlebars](https://github.com/express-handlebars/express-handlebars/). If you could create an issue on that repo we could try to help.
