### ISSUE TITLE
Not able to render external css which has been bundled using webpack 

### ISSUE THREAD

**Issue by akshayp660** [ericf/express-handlebars#288]
In simple words, I am trying to add stylesheet by the twitter-bootstrap package which I bundled using laravel-mix(webpack) to my .hbs template. but not able to load this error is being logged into the browser console.

**Refused to apply style from .css file because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.**

I am new to express handle-bar, please help

**Comment by UziTech** [comment]
This repo is no longer maintained. New versions of express-handlebars are maintained at https://github.com/express-handlebars/express-handlebars. If you create an issue there we can try to help you.
