### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [ericf/express-handlebars#290]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by UziTech** [comment]
All new development of express-handlebars is done on a new repo [express-handlebars/express-handlebars](https://github.com/express-handlebars/express-handlebars). 

You can email me at tony@brix.ninja if you have security concerns.

**Comment by UziTech** [comment]
If the concern is with this repo and not the npm package `express-handlebars` then good luck reaching @ericf I tried for a while and eventually had to fork it.

**Comment by agustingianni** [comment]
Hello @UziTech thank you for the answer! I will contact you if there is any concerns about your fork. Thanks again.
