### ISSUE TITLE
Question: How precompile actually works?

### ISSUE THREAD

**Issue by davidnguyen11** [ericf/express-handlebars#292]
I investigated the code. So far I understand every time load page, it store the `compiled template` to variable `cache` and next time it get template from cache rather than running compile function again. Question:

- If the lib already had `cache`, why do we need `precompile`?

**Comment by UziTech** [comment]
Makes it easier to use on the client side. https://handlebarsjs.com/installation/precompilation.html

All new development of express-handlebars is done on a new repo [express-handlebars/express-handlebars](https://github.com/express-handlebars/express-handlebars). Please create an issue there if you need more assistance.
