### ISSUE TITLE
res.render from subdirectory in views

### ISSUE THREAD

**Issue by KrisLau** [ericf/express-handlebars#296]
I'm trying to render my view from my `emails` subdirectory but I cant seem to get it to work. To clarify, I don't want to change the default directory for handlebars and I just want to change it for this path.

Directory:
`views/emails/invite.handlebars`

Code:
```
router.get('/', (req, res) => {
    res.render('emails/invite.handlebars', {layout: false});
});
```

Error: `Failed to lookup view "emails/invite.handlebars" in views directory "./views"`

Other things I've tried:
- `/emails/invite.handlebars`
- `../views/emails/invite.handlebars`

**Comment by UziTech** [comment]
This repo is no longer active. all new development on express-handlebars is done on https://github.com/express-handlebars/express-handlebars.

Please move your issue there to get help.

**Comment by KrisLau** [comment]
@UziTech thanks will do!
