### ISSUE TITLE
Update README.md as per the configuration.

### ISSUE THREAD

**Issue by rahimnagori** [ericf/express-handlebars#302]
Current installation instructions are throwing an error.
![image](https://user-images.githubusercontent.com/42448371/189184850-ae541e9a-d599-44e3-a7f9-0f5852269b1b.png)

This needs to be updated from
`app.engine('handlebars', exphbs());`
to
`app.engine('handlebars', exphbs.engine());`

For the I want to raise a PR.

**Comment by UziTech** [comment]
you are looking in the wrong repo. express-handlebars has been moved to https://github.com/express-handlebars/express-handlebars

**Comment by rahimnagori** [comment]
Thanks for the clarification.
