### ISSUE TITLE
How to dynamically include partials

### ISSUE THREAD

**Issue by Raidok** [ericf/express-handlebars#63]
I have a JSON markup something along the lines like this:

**markup/frontpage.json**:

```
{
  title: 'Front page',
  children: [
    {
      partial: 'list',
      children: [
        { partial: 'listelement', content: 'Element 1' },
        { partial: 'listelement', content: 'Element 1' }
      ]
    }
  ]
}
```

And handlebars templates:

**views/frontpage.handlebars**:

```
<h1>{{title}}
{{{partial children}}}
```

**views/partials/list.handlebars**:

```
<div class="list-group">
  {{{partial children}}}
</div>
```

**views/partials/listelement.handlebars**:

```
<a href="#" class="list-group-item">{{content}}</a>
```

I would like to generate HTML based on similar markups but express3-handlebars expects the `partial` to be a name of a partial in `{{> partial}}` but I would like it to dynamically included by the value of this variable in the scope. It looks like a job for a helper but I can't seem to figure it out.

Has anybody else figured this one out already?

**Comment by ericf** [comment]
Dynamic partials are now supported in Handlebars 3.0, and PR #105 adds support for Handlebars 3.0.
