### ISSUE TITLE
Intergrating with Swag

### ISSUE THREAD

**Issue by markbarton** [ericf/express-handlebars#69]
I looked at the closed issue (#47) but can't seem to get Swag - https://github.com/elving/swag to work with hbs - using Express 4 if this makes any difference.

Swag wants to call registerHelpers on the handlebars instance - this method doesnt exist - I am probably missing something obvious.

Any help?

**Comment by molinto** [comment]
Brilliant timesaver thanks Mark!

**Comment by wascou** [comment]
Cheers
