### ISSUE TITLE
AngularJS - just a FYI

### ISSUE THREAD

**Issue by markbarton** [ericf/express-handlebars#85]
Just a quick note in case anyone else was trying to combine handlebars templates with AngularJS client side.

I couldn't find anywhere within the Handlebars configuration to change the delimiters from {{ }} so I could include AngularJS code so to solve this problem I modified my AngularJS code to use a different delimiter:

    //This allows angular binding inside a handlebars template
    function handlebarsBinding($interpolateProvider) {
        $interpolateProvider.startSymbol('{[{').endSymbol('}]}');
    }
    angular.config(handlebarsBinding)

**Comment by marksyzm** [comment]
You could also put the HTML files in the public directory, and set it up so you use the .html extension. That way you can use them in both server and client side code.

**Comment by ericf** [comment]
Closing this since it will show up when someone searches "Angular" in this repo.

**Comment by nicholaswmin** [comment]
@ericf Is it possible to have the Handlebars delimiter configurable? i.e use `%%` instead of `{{`.

Remembering to escape the delimiter every time is error prone.
