### ISSUE TITLE
Access to `Handlebars.partials` inside global helpers file

### ISSUE THREAD

**Issue by TuxSudo** [ericf/express-handlebars#89]
We want to be able to render partials from inside helpers. For example, in our global helpers file, when we try something like:

```
var Handlebars = require('handlebars');

module.exports = {
    something: function(options) {
        var partial = Handlebars.partials['partial-name'];
              html = partial(options.hash);
        //....... 
    }
}
```

That partial `partial-name` is not available because `Handlebars.partials` is an empty object `{}`.

What is the best way to create/import/inject the `Handlebars.partials` object (as defined in the `partialsDir` option) so our helpers can instantiate them?

Thanks in advance!

**Comment by ericf** [comment]
This seems very much related to #101, and in PR #105 I'm now passing along the `partials` to the data channel during rendering making them available inside of helpers via `options.data.ExpressHandlebars.partials`.

Let me know if you think that will solve what you're after here, and if so, I'll close this out once #105 is merged.

**Comment by TuxSudo** [comment]
Not particularly, but that's ok. The goal is to allow development of helpers and partials that work both server and clientside. Clientside, handlebars puts partials at `Handlebars.partials`. So, I'd still have to register them globally anyway with the proposed solution. But I will close this and potentially submit a pull request later.  

Thanks for your work on this. :+1:

**Comment by rahil051** [comment]
@tuxsudo thankyou for the hint. I was wondering how can I access Handlebars instance in my helpers file when using express-handlebars package.

this is the hack I used

```javascript
// app.js

var hbs = exhbs.create({
    defaultLayout: 'main',
    helpers: require('./lib/hbs-helpers'),
    // other options
});
```
and in lib/hbs-helpers.js
```javascript
Handlebars = require('handlebars'); // the official handlebars package
module.exports = (function(Handlebars) {
   fallback: function(actual, defaultValue) {
       var out = actual || defaultVal;
       return new Handlebars.SafeString(out); // now I can access Handlebars instance
   }
})(Handlebars);
```
This is a hack as I am not good with documentations so is there an integration with express-handlebars.
