### ISSUE TITLE
Works on Azure?

### ISSUE THREAD

**Issue by dickieirwin** [ericf/express-handlebars#90]
Has anyone got this working on Azure?

**Comment by molant** [comment]
Yes, I have it running on https://remote.modern.ie which runs an Azure Website.
What problem do you have?

**Comment by ericf** [comment]
@molant thanks for that info!

**Comment by ericf** [comment]
@dickieirwin I'm going to close this issue, but feel free to re-open if you're having a problem that you think is a bug in this package.
