### ISSUE TITLE
partial compiler option for preventIndent 

### ISSUE THREAD

**Issue by ericlowry** [ericf/express-handlebars#95]
With Handlebars 2.0, partials get indented automatically in the resulting document.
This is great most of the time, unless you are generating content with \<pre\> or \<textarea\> tags where whitespace matters.

I need a way to specify that I want to set the compiler options to include the 'preventIndent = true' flag when loading partials...

Thanks!

**Comment by ericf** [comment]
In #105 I've added a new config property: `compilerOptions`, plus I've replaced the `compileTemplate()` hook with `_compileTemplate()` and `_precompileTemplate()` both of which are passed the `compilerOptions`. Let me know if this new options satisfies what you are after here.

**Comment by ericf** [comment]
Closing this since #105 was merged.

**Comment by jme783** [comment]
Hi there, I'm running into this and would like to use the new `compilerOptions` config property with `preventIndent`. After trying to implement, I'm still noticing an indent in my preformatted code. Does this look correct? 

```
app.engine('.hbs', exphbs({
  defaultLayout: 'main',
  extname: '.hbs',
  partialsDir: 'views/partials/',
  compilerOptions: {
    preventIndent: true
  }
}));
app.set('view engine', '.hbs');

```

Any help would be greatly appreciated! Thanks!

**Comment by jme783** [comment]
Solved! I just had to make sure I was updated to the newest version of `express-handlebars`, 2.0.0 :+1:
