### ISSUE TITLE
Support callbacks with then/nodeify module

### ISSUE THREAD

**Issue by JibSales** [ericf/express-handlebars#99]
I'm not trying to be "that guy" but as a long time consumer of this module I'm not upgrading to the 1.0 branch because of the move away from standard callbacks to Promises. I understand the aesthetic and flow control benefits gained, however, the public API should follow the best practices of the community. I shouldn't have to work around your internal design choices.

Please consider providing a dual API until Promises are standardized in the Javascript/Node community. Since you are using the then/promise module, might you also consider their https://github.com/then/nodeify module to integrate callback support?

**Comment by ericf** [comment]
Promises are a standard part of JavaScript as of ES6, they're implemented in browsers, and will be in Node.js (and are in the IO.js fork). The switch to using Promises reduced the LOC by 1/3, made this package faster, and made the code easier to read.

**Comment by JibSales** [comment]
I'm not asking for you to remove Promise support, simply to provide both callbacks and Promises in your public facing API. While, yes, Promises are the future of handling async code, the future is still the future. They are not currently present in Node stable and ES6 is still a working draft — thus the reason you are depending on the `then/promise` module. Can you provide benchmarks for the speed claims?
